CREATE TABLE
    VERSION
    (
        MAJOR_RELEASE_ID INTEGER NOT NULL,
		MINOR_RELEASE_ID INTEGER NOT NULL,
		PATCH_RELEASE_ID INTEGER NOT NULL,
        CONSTRAINT PKEY_VERSION PRIMARY KEY (MAJOR_RELEASE_ID, MINOR_RELEASE_ID, PATCH_RELEASE_ID)
    );