CREATE TABLE ROBOTAIRBLOWSETTINGS (
        ID INTEGER NOT NULL,
        CLAMPING INTEGER NOT NULL,
        BOTTOMCOORD INTEGER NOT NULL,
        TOPCOORD INTEGER NOT NULL,
        CONSTRAINT PKEY_ROBOTAIRBLOWSETTINGS PRIMARY KEY (ID, CLAMPING),
        CONSTRAINT AIRBLOWSETTINGS_ROBOTACTIONSETTINGS FOREIGN KEY (ID) REFERENCES ROBOTACTIONSETTINGS (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
        CONSTRAINT AIRBLOWSETTINGS_CLAMPING FOREIGN KEY (CLAMPING) REFERENCES CLAMPING (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
        CONSTRAINT BOTTOMCOORD FOREIGN KEY (BOTTOMCOORD) REFERENCES COORDINATES (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
        CONSTRAINT TOPCOORD FOREIGN KEY (TOPCOORD) REFERENCES COORDINATES (ID) ON DELETE CASCADE ON UPDATE RESTRICT
);
