DROP TABLE CNC_OPTION;
DROP TABLE CNC_OPTION_TYPE;

CREATE TABLE
    CNC_OPTION_TYPE
    (
        ID INTEGER NOT NULL,
        NAME VARCHAR(100) NOT NULL,
        CONSTRAINT PKEY_OPTION_TYPE PRIMARY KEY (ID)
    );
    
CREATE TABLE
    CNC_OPTION
    (
        CNC_ID INTEGER NOT NULL,
        OPTION_ID INTEGER NOT NULL,
        OPTION_VALUE BOOLEAN NOT NULL,
        CONSTRAINT PKEY_CNC_OPTION PRIMARY KEY (CNC_ID, OPTION_ID),
        CONSTRAINT FK_CNC_OPTION_MACHINE_ID FOREIGN KEY (CNC_ID) REFERENCES CNCMILLINGMACHINE (ID) ON DELETE CASCADE,
        CONSTRAINT FK_CNC_OPTION_TYPE_ID FOREIGN KEY (OPTION_ID) REFERENCES CNC_OPTION_TYPE (ID) ON DELETE CASCADE
    );
    
INSERT INTO CNC_OPTION_TYPE VALUES (1, 'TIM_ALLOWED');
INSERT INTO CNC_OPTION_TYPE VALUES (2, 'MACHINE_AIRBLOW'); 

INSERT INTO CNC_OPTION (
        SELECT CNCMILLINGMACHINE.ID, 1, CNCMILLINGMACHINE.TIM_ALLOWED 
          FROM CNCMILLINGMACHINE );
              
INSERT INTO CNC_OPTION VALUES (1, 2, 'false'); 

ALTER TABLE CNCMILLINGMACHINE DROP COLUMN TIM_ALLOWED;

ALTER TABLE DEVICEACTIONSETTINGS ADD COLUMN MACHINE_AIRBLOW BOOLEAN NOT NULL DEFAULT FALSE;

