ALTER TABLE WORKAREA ADD COLUMN PRIO_IF_CLONED INTEGER NOT NULL DEFAULT 1;
ALTER TABLE WORKAREA ADD CONSTRAINT UNIQUE_PRIO_CLONE UNIQUE (ZONE, USERFRAME, PRIO_IF_CLONED);

ALTER TABLE DEVICEACTIONSETTINGS ADD COLUMN NB_CNC_ACTION INTEGER;