INSERT INTO DEVICE VALUES (7,'REVERSAL UNIT',7);
INSERT INTO ZONE VALUES (7,7,'REVERSAL UNIT MAIN ZONE', 0);

CREATE TABLE
    REVERSALUNIT
    (
        ID INTEGER NOT NULL,
        STATION_HEIGHT FLOAT DEFAULT 0 NOT NULL,
        CONSTRAINT REVERSALUNIT_DEVICE FOREIGN KEY (ID) REFERENCES DEVICE (ID)
    );
    
INSERT INTO REVERSALUNIT (ID, STATION_HEIGHT) VALUES (7, 0.0);    
 
INSERT INTO COORDINATES (X, Y, Z, W, P, R) VALUES (0,0,0,0,0,0);

INSERT INTO USERFRAME (NUMBER, ZSAFE, LOCATION, NAME) 
        SELECT 9, 20.0, MAX(ID), 'REVERSAL UNIT' 
        FROM COORDINATES;
    
INSERT INTO WORKAREA (ZONE, USERFRAME, NAME) 
        (SELECT ZONE.ID, USERFRAME.ID, 'REVERSAL UNIT'
          FROM ZONE, USERFRAME
         WHERE ZONE.DEVICE = 7 
           AND USERFRAME.NAME = 'REVERSAL UNIT'
        );

INSERT INTO COORDINATES (X, Y, Z, W, P, R) VALUES (0,0,0,0,0,0);
INSERT INTO COORDINATES (X, Y, Z, W, P, R) VALUES (0,0,0,0,0,0);
INSERT INTO COORDINATES (X, Y, Z, W, P, R) VALUES (0,0,0,0,0,0);        
        
INSERT INTO CLAMPING (TYPE, RELATIVE_POSITION, SMOOTH_TO, SMOOTH_FROM, HEIGHT, NAME, FIXTURE_TYPE)
          SELECT 3, MAX(ID), (MAX(ID) - 1), (MAX(ID) -2),  0, 'Reversal Unit', 0       
           FROM COORDINATES;        

INSERT INTO WORKAREA_CLAMPING (WORKAREA, CLAMPING)
        (SELECT WORKAREA.ID,  CLAMPING.ID 
           FROM WORKAREA, CLAMPING
          WHERE WORKAREA.NAME = 'REVERSAL UNIT'
            AND CLAMPING.NAME = 'Reversal Unit'
        );

INSERT INTO MCODE VALUES (3,2, 1, 'loadR', true, false, false, false, false, false);
INSERT INTO MCODE VALUES (4,3, 1, 'unloadR', true, false, false, false, false, false);

INSERT INTO WORKAREA (ZONE, USERFRAME, NAME)
         (
                SELECT WORKAREA.ZONE
                      ,WORKAREA.USERFRAME
                      ,'MAIN REV'
                  from workarea 
                 where userframe = 1
                );

insert into workarea_clamping (workarea, clamping ) 
(
        select workarea.id, clamping
         from workarea_clamping, workarea
        where workarea = 1
          and workarea.name = 'MAIN REV'
        );

INSERT INTO WORKPIECETYPE VALUES (3, 'HALF_FINISHED');

ALTER TABLE DEVICEACTIONSETTINGS ADD COLUMN WORKPIECE INTEGER;
ALTER TABLE DEVICEACTIONSETTINGS ADD CONSTRAINT DEVICEACTIONSETTINGS_WORKPICE FOREIGN KEY (WORKPIECE) REFERENCES WORKPIECE (ID) ON
    DELETE
        SET NULL;
 