CREATE TABLE PALLETSETTINGS (
	ID INTEGER NOT NULL,
    RAWWORKPIECE INTEGER NOT NULL,
    FINISHEDWORKPIECE INTEGER NOT NULL,
    LAYERS INTEGER NOT NULL,
    AMOUNT INTEGER NOT NULL,
    GRID_ID INTEGER NOT NULL,
    PALLET_LAYOUT_ID INTEGER NOT NULL,
	CONSTRAINT PKEY_PALLETSETTINGS PRIMARY KEY (ID),
    CONSTRAINT PALLETSETTINGS_FINISHEDWORKPIECE FOREIGN KEY (FINISHEDWORKPIECE) REFERENCES
        WORKPIECE (ID) ON
    DELETE
        CASCADE,
    CONSTRAINT PALLETSETTINGS_RAWWORKPIECE FOREIGN KEY (RAWWORKPIECE) REFERENCES
        WORKPIECE (ID) ON
    DELETE
        CASCADE,
    CONSTRAINT PALLETSETTINGS_PALLET_LAYOUT_ID FOREIGN KEY (PALLET_LAYOUT_ID) REFERENCES
        PALLETLAYOUT (ID) ON
    DELETE
        CASCADE,
    CONSTRAINT PALLETSETTINGS_ID FOREIGN KEY (ID) REFERENCES DEVICESETTINGS (ID)
    ON
    DELETE
        CASCADE
    ON
    UPDATE
        RESTRICT
);
