INSERT INTO CNC_OPTION_TYPE (ID, NAME) VALUES (4, 'CLAMPING_PRESSURE_SELECTABLE');
INSERT INTO CNC_OPTION (CNC_ID, OPTION_ID, OPTION_VALUE) VALUES (1, 4, false);
ALTER TABLE DEVICEACTIONSETTINGS ADD COLUMN CLAMPING_PRESSURE_LOW BOOLEAN DEFAULT FALSE NOT NULL;